package de.TeutonStudio.MathematikKnoten

import de.TeutonStudio.KnotenKartenVerwalter.daten.*
import de.TeutonStudio.MathematikKartenAdapter.BedingterWert
import de.TeutonStudio.MathematikKartenAdapter.KnotenAuswertungsKontext
import de.TeutonStudio.MathematikRechenSystem.kern.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class DifferentialKnotenTest {
    private val register = GesamterMathematikAuswerter.erzeugeRegister()
    private fun kontext(knoten: KnotenDaten, eingaben: Map<String, BedingterWert> = emptyMap()) = KnotenAuswertungsKontext(knoten, eingaben, RechenKontext())
    private fun quadratischeMethode(): Methode { val x=Variable("x"); return Methode("f",listOf(x),Potenz(x,RationaleZahl.von(2)),ReelleZahlen,mapOf("x" to ReelleZahlen)) }
    @Test fun `Vorlagenkatalog enthaelt genau einen gemeinsamen Differentialknoten`() { val v=alleMathematikKnotenVorlagen().filter{it.art==DIFFERENTIAL_KNOTEN_ART}; assertEquals(1,v.size); assertEquals(DifferentialAusgabeForm.METHODE.name,v.single().standardParameter[DIFFERENTIAL_AUSGABEFORM_PARAMETER]) }
    @Test fun `Moduswechsel zeigt nur benoetigte Handles und verwendet fremde Rollen nicht weiter`() { val m=DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero); val mi=m.anschlüsse.single{it.richtung==AnschlussRichtung.Eingang&&it.name=="methode"}; val mo=m.anschlüsse.single{it.richtung==AnschlussRichtung.Ausgang&&it.name=="methode"}; val t=konfiguriereDifferentialKnoten(m,DifferentialAusgabeForm.TERM); assertEquals(setOf("term","nach"),t.anschlüsse.map{it.name}.toSet()); assertTrue(t.anschlüsse.none{it.name=="ordnung"||it.name=="methode"}); assertTrue(t.anschlüsse.none{it.id==mi.id||it.id==mo.id}); val wm=konfiguriereDifferentialKnoten(t,DifferentialAusgabeForm.METHODE); assertNotEquals(mi.id,wm.anschlüsse.single{it.richtung==AnschlussRichtung.Eingang&&it.name=="methode"}.id) }
    @Test fun `Diagnose meldet verbundene Handles vor Modustrennung`() { val k=DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero); val o=k.anschlüsse.single{it.name=="ordnung"}.id; val d=diagnostiziereDifferentialModusWechsel(k,DifferentialAusgabeForm.TERM,setOf(o)); assertTrue(d.trenntVerbindungen); assertEquals(setOf(o),d.verbundeneEntfernteAnschlussIds) }
    @Test fun `Methodenmodus berechnet zweite Ableitung aus gespeichertem Fallback`() { val k=DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero).copy(parameter=DifferentialKnotenVorlagen.Differential.standardParameter+(DIFFERENTIAL_ORDNUNG_PARAMETER to "2")); val e=assertNotNull(register.finde(DIFFERENTIAL_KNOTEN_ART)).auswerten(kontext(k,mapOf("methode" to BedingterWert(quadratischeMethode())))); val m=assertIs<Methode>(e.ausgaben.getValue("methode").objekt); assertEquals(RationaleZahl.von(2),m.vorschrift); assertTrue(e.warnungen.any{it.contains("BERECHNET")}); assertTrue(e.warnungen.any{it.contains("D_{2}(f)")}) }
    @Test fun `verbundene symbolische Ordnung bleibt bedingt in N null`() { val k=DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero); val n=Variable("n"); val e=assertNotNull(register.finde(DIFFERENTIAL_KNOTEN_ART)).auswerten(kontext(k,mapOf("methode" to BedingterWert(quadratischeMethode()),"ordnung" to BedingterWert(n)))); val m=assertIs<Methode>(e.ausgaben.getValue("methode").objekt); assertEquals("f^{(n)}",m.name); assertTrue(e.ausgaben.getValue("methode").annahmen.isNotEmpty()) }
    @Test fun `Termmodus koppelt dx an gespeicherte Quellen ID`() { val x=Variable("x"); val k=konfiguriereDifferentialKnoten(DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero),DifferentialAusgabeForm.TERM).copy(parameter=DifferentialKnotenVorlagen.Differential.standardParameter+mapOf(DIFFERENTIAL_AUSGABEFORM_PARAMETER to DifferentialAusgabeForm.TERM.name,DIFFERENTIAL_QUELLEN_ID_PARAMETER to "quelle.x")); val e=assertNotNull(register.finde(DIFFERENTIAL_KNOTEN_ART)).auswerten(kontext(k,mapOf("term" to BedingterWert(Potenz(x,RationaleZahl.von(2))),"nach" to BedingterWert(x)))); val d=assertIs<DifferentialTerm>(e.ausgaben.getValue("term").objekt); assertEquals("quelle.x",d.quellenId); assertEquals("dx",d.differentialVariable.zuLatex()); assertTrue(d.zuLatex().contains("\\cdotdx")) }
    @Test fun `negative Ordnung erzeugt einen Konfigurationsfehler`() { val k=DifferentialKnotenVorlagen.Differential.erzeuge(GraphPunkt.Zero).copy(parameter=DifferentialKnotenVorlagen.Differential.standardParameter+(DIFFERENTIAL_ORDNUNG_PARAMETER to "-1")); val e=assertNotNull(register.finde(DIFFERENTIAL_KNOTEN_ART)).auswerten(kontext(k,mapOf("methode" to BedingterWert(quadratischeMethode())))); assertTrue(e.ausgaben.isEmpty()); assertTrue(e.fehler.orEmpty().contains("ℕ₀")) }
    @Test fun `historische Ableitung und Differentialterm migrieren idempotent`() { val a=KnotenDaten(art="mathematik.ableitung",name="Alt",position=GraphPunkt.Zero,parameter=mapOf("ordnung" to "3")); val t=KnotenDaten(art="mathematik.differentialTerm",name="Altterm",position=GraphPunkt(1f,1f),parameter=mapOf("quellenId" to "quelle.alt")); val m=KartenDaten(name="Alt",knoten=listOf(a,t)).migriereDifferentialKnoten(); assertEquals(setOf(DIFFERENTIAL_KNOTEN_ART),m.knoten.map{it.art}.toSet()); assertEquals("3",m.knoten[0].parameter[DIFFERENTIAL_ORDNUNG_PARAMETER]); assertEquals(DifferentialAusgabeForm.TERM.name,m.knoten[1].parameter[DIFFERENTIAL_AUSGABEFORM_PARAMETER]); assertEquals("quelle.alt",m.knoten[1].parameter[DIFFERENTIAL_QUELLEN_ID_PARAMETER]); assertEquals(m,m.migriereDifferentialKnoten()) }
}
